:sourcesdir: ../../source

[[security]]
== Security Implications When Using REST API

Universal REST API provides powerful means to deal with arbitrary data from domain model without creation of custom REST endpoints. However, if you enable the REST API in your application, you must configure {manual}/security_subsystem.html[security] (Roles/Access Groups) and always keep it in actual state on a production system in order to prevent access to some sensitive data.

Here are some rules you should follow when the REST API is turned on:

* Always disable access to the REST API for roles/users which are not supposed to use it. See `CUBA > REST API > Use REST API` specific permission in the role editor screen.
* Use deny-by-default strategy: always assign `DENYING` role to users which have access to the REST API. Project model changes over time - it’s easy to miss adding granular restrictions.
* Always configure and assign access group constraints for non-common entities to the REST API users.
* Remember that `EntityManager` does not impose access group constraints, so consider using `DataManager` in middleware services exposed to the REST API.
* Remember that entity attribute restrictions are not imposed by a `DENYING` role. Setup permissions for each entity attribute individually.
* Specify a unique <<cuba.rest.client.secret,client secret>> in production environment.

If you have troubles configuring fine-grained security for your project, consider implementing custom endpoints instead of the universal REST API.
