:sourcesdir: ../../source

[[security]]
== Безопасность приложений, использующих REST API

REST API определяет свою собственную {manual}/roles.html#security_scope[область действия] - `REST`. Для пользователей, входящих в систему через REST API, необходимо сконфигурировать отдельный набор {manual}/roles.html[ролей], включающий разрешение `cuba.restApi.enabled`. Если этого не сделать, пользователи не смогут входить через REST.

=== Предыдущая реализация

Если ваш проект использует предыдущую версию CUBA или мигрирует на версию CUBA 7.2, то используется {manual}/legacy_roles.html[предыдущая реализация ролей и разрешений]. Поэтому, если вы используете REST API в приложении, вы должны настроить подсистему безопасности(Roles/Access Groups) и всегда поддерживать ее в актуальном состоянии в рабочей системе, чтобы предотвратить доступ к конфиденциальным данным.

Необходимо придерживаться следующих правил при использовании REST API:

* Всегда отключайте доступ к REST API для ролей и пользователей, которые не должны его использовать. Смотрите специфическое разрешение  `CUBA > REST API > Use REST API` в экране редактирования ролей.
* Используйте стратегию "запретить по-умолчанию": всегда назначайте роль `DENYING` пользователям, имеющим доступ к REST API. Модель проекта меняется со временем, легко пропустить добавление детализированных ограничений.
* Всегда настраивайте ограничения групп доступа к сущностями, не являющимися общими, для пользователей, имеющим доступ к REST API.
* Помните, что `EntityManager` не накладывает ограничения групп доступа, поэтому используйте `DataManager` в сервисах среднего слоя, доступных для REST API.
* Помните, что ограничения атрибутов сущностей не накладываются ролью `DENYING`. Настраивайте разрешения для каждого атрибута сущности отдельно.
* Задайте уникальный <<cuba.rest.client.secret,пароль клиента>> в режиме эксплуатации.

Если у вас возникли проблемы с настройкой детализированной защиты для вашего проекта, рассмотрите возможность реализации пользовательских методов вместо универсального REST API.
